name: Sync README.md with readme.txt

on:
  push:
    branches:
      - main
    paths:
      - 'readme.txt'

jobs:
  sync-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Convert readme.txt to README.md
        run: |
          # Create a bash script to convert readme.txt to README.md
          cat > convert.sh <<'EOF'
          #!/bin/bash

          # Create the README.md file
          echo "# Glass Analytics

          A WordPress plugin for website analytics tracking and reporting.
          " > README.md

          # Convert WordPress headings to Markdown and append to README.md
          cat readme.txt | sed 's/=== \(.*\) ===/# \1/g' | \
                          sed 's/== \(.*\) ==/## \1/g' | \
                          sed 's/= \(.*\) =/### \1/g' | \
                          sed 's/^\* /- /g' >> README.md
          EOF
          
          # Make the script executable and run it
          chmod +x convert.sh
          ./convert.sh
          
      - name: Commit and push changes if README.md has changed
        run: |
          git config --global user.name 'GitHub Actions Bot'
          git config --global user.email 'actions@github.com'
          
          # Check if README.md has changed
          if git diff --exit-code README.md; then
            echo "No changes to README.md"
          else
            git add README.md
            git commit -m "Update README.md from readme.txt [skip ci]"
            git push
          fi