name: Protect README.md

on:
  pull_request:
    paths:
      - 'README.md'

jobs:
  check_readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Check if README.md was modified
        id: check_modified
        run: |
          PR_FILES=$(gh api repos/${{ github.repository }}/pulls/${{ github.event.pull_request.number }}/files --jq '.[].filename')
          if echo "$PR_FILES" | grep -q "README.md"; then
            echo "README.md was modified directly. This file should only be modified by GitHub Actions."
            echo "::set-output name=modified::true"
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Comment on PR
        if: steps.check_modified.outputs.modified == 'true'
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: '⚠️ **WARNING**: Please do not modify README.md directly. This file is automatically generated from readme.txt. Please edit readme.txt instead, and README.md will be updated automatically.'
            })
            
      - name: Fail check
        if: steps.check_modified.outputs.modified == 'true'
        run: |
          echo "README.md should not be modified directly. Please edit readme.txt instead."
          exit 1