name: Sync README.md with readme.txt

on:
  push:
    branches:
      - main
    paths:
      - 'readme.txt'

jobs:
  sync-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'
          
      - name: Convert readme.txt to README.md
        run: |
          # Create a PHP script to convert readme.txt to README.md
          cat > convert.php <<'EOF'
          <?php
          // Read the readme.txt file
          $readme = file_get_contents('readme.txt');
          
          // Convert WordPress headings to Markdown headings
          $readme = preg_replace('/=== (.*) ===/i', '# $1', $readme);
          $readme = preg_replace('/== (.*) ==/i', '## $1', $readme);
          $readme = preg_replace('/= (.*) =/i', '### $1', $readme);
          
          // Convert WordPress bullet points to Markdown bullet points
          $readme = preg_replace('/^\* /m', '- ', $readme);
          
          // Add the banner section
          $banner = "A WordPress plugin for website analytics tracking and reporting.\n\n";
          $readme = preg_replace('/(# Glass Analytics)/', "$1\n\n$banner", $readme);
          
          // Write the content to README.md
          file_put_contents('README.md', $readme);
          EOF
          
          # Run the PHP script
          php convert.php
          
      - name: Commit and push changes if README.md has changed
        run: |
          git config --global user.name 'GitHub Actions Bot'
          git config --global user.email 'actions@github.com'
          
          # Check if README.md has changed
          if git diff --exit-code README.md; then
            echo "No changes to README.md"
          else
            git add README.md
            git commit -m "Update README.md from readme.txt [skip ci]"
            git push
          fi